# Generated by Django 3.1.3 on 2020-11-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('priority', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('complaint_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint_category')),
            ],
        ),
    ]
