# Generated by Django 3.1.3 on 2020-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20201107_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_user',
            name='complaint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
