# Generated by Django 3.1.3 on 2020-11-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_complaint_user_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint_user',
            old_name='complaint',
            new_name='complaint_info',
        ),
    ]
