# Generated by Django 3.1.3 on 2020-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.SmallIntegerField(choices=[(1, 'MSEB Chief Engineer'), (2, 'Municipal Commissioner'), (3, 'Water Conservation officer'), (4, 'Public grievance officer'), (5, 'Department Safety Officer')], default=0),
        ),
    ]
