# Generated by Django 3.1.3 on 2020-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
