# Generated by Django 3.1.3 on 2020-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201106_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='upload_aadhar',
            field=models.FileField(blank=True, default=None, null=True, upload_to='user_files'),
        ),
        migrations.AddField(
            model_name='users',
            name='upload_id',
            field=models.FileField(blank=True, default=None, null=True, upload_to='user_files'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
