# Generated by Django 3.1.3 on 2020-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201106_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar_no',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_aadhar',
            field=models.FileField(default=None, upload_to='user_files'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_id',
            field=models.FileField(default=None, upload_to='user_files'),
        ),
    ]
