# Generated by Django 3.1.3 on 2020-11-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201106_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='upload_aadhar',
            field=models.FileField(upload_to='user_files'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_id',
            field=models.FileField(upload_to='user_files'),
        ),
    ]
